print("welcome")
entrada1=input("escriba un numero")
number1=int(entrada1)
entrada2=input("escriba el segundo numero")
number2=int(entrada2)
print("el resultado de la suma es")
print(number1+number2)
print("el resultado de la resta es")
print(number1-number2)
print("el resultado de la multiplicacion es")
print(number1*number2)
print("el resultado de la division es")
print(number1/number2)